In [1]:
import sqlite3

# Create/connect DB
conn = sqlite3.connect('demo.db')
c = conn.cursor()

# Create table
c.execute('''CREATE TABLE IF NOT EXISTS households
             (id INTEGER PRIMARY KEY, gapaname TEXT, owned INTEGER, total INTEGER)''')

# Insert data
c.execute("INSERT OR IGNORE INTO households VALUES (1, 'Demo Gaunpalika', 100, 150)")

# Query
c.execute("SELECT * FROM households")
print(c.fetchall())  # Output: [(1, 'Demo Gaunpalika', 100, 150)]

conn.commit()
conn.close()

[(1, 'Demo Gaunpalika', 100, 150)]

In [5]:
# Pandas way – handles nesting automatically
import requests
import pandas as pd

# Fetch
r = requests.get('https://pokeapi.co/api/v2/pokemon/pikachu')
data = r.json()

# Process
# Manual extraction – understand the JSON
types = [t['type']['name'] for t in data['types']]
df = pd.DataFrame([{
    'name': data['name'],
    'height': data['height'],
    'weight': data['weight'],
    'types': types
}])
df
# Output: DataFrame with Pikachu stats

df_full = pd.json_normalize(data)
print(df_full.columns[:20])  # Shows all flattened columns
df_full[['name', 'height', 'weight', 'types']].head()

Index(['abilities', 'base_experience', 'forms', 'game_indices', 'height',
       'held_items', 'id', 'is_default', 'location_area_encounters', 'moves',
       'name', 'order', 'past_abilities', 'past_types', 'stats', 'types',
       'weight', 'cries.latest', 'cries.legacy', 'species.name'],
      dtype='object')

      name  height  weight                                              types
0  pikachu       4      60  [{'slot': 1, 'type': {'name': 'electric', 'url...

In [6]:
selected = {
    'name': data['name'],
    'height': data['height'],
    'weight': data['weight'],
    'base_experience': data['base_experience'],
    'types': ', '.join(t['type']['name'] for t in data['types'])
}
df_clean = pd.DataFrame([selected])
df_clean

      name  height  weight  base_experience     types
0  pikachu       4      60              112  electric

In [7]:
from zeep import Client

client = Client('https://www.dataaccess.com/webservicesserver/NumberConversion.wso?WSDL')
result = client.service.NumberToWords(2025)

# Process (simple string)
print(f"Processed: {result.upper()}")  # ONE THOUSAND TWENTY FIVE

# For XML: Use xml.etree.ElementTree to parse

ModuleNotFoundError: No module named 'zeep'

In [1]:
student = {
    "name": "Sahaj",
    "age": 20,
    "course": "AI"
}

print(student["name"])

Sahaj

In [ ]:
student = {             # Using dictionary literal
    "name": "Sahaj",
    "age": 20,
    "course": "AI"
}

print(student)

{'name': 'Sahaj', 'age': 20, 'course': 'AI'}

In [ ]:
students=[
    'sahaj', 'aayush', 'bikash','ram'  #list of students
]
students.sort()
print(students)

['aayush', 'bikash', 'ram', 'sahaj']